config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  resources :bars do
    resources :tournaments, only: [:new, :create]
  end
  resources :tournaments, except: [:new, :create] do
    get "playground", to: "tournaments#playground"
    resources :players
    resources :reviews, only: :create
  end
  resources :users
  get "dashboard", to: "users#dashboard"
  resources :scores, only: :update
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "rankings", to: "pages#rankings"

  resources :games, only: [] do
    member do
      patch :update_scores
    end
  end
end

app/models/bar.rb
class Bar < ApplicationRecord
  has_many :availabilities
  has_many :tournaments
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  before_action :set_bar, only: [ :show, :edit, :update, :destroy ]

  def index
    @bars = policy_scope(Bar)

    @hash = Gmaps4rails.build_markers(@bars) do |bar, marker|
      marker.lat bar.latitude
      marker.lng bar.longitude
      # marker.infowindow render_to_string(partial: "/bars/map_box", locals: { bar: bar })
    end
  end

  def show
    @tournament = Tournament.new()
  end

  def new
    @bar = Bar.new()
  end

  def create
    @bar = Bar.new(bar_params)
    if @bar.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @bar.update(bar_params)
    if @bar.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @bar.destroy
    redirect_to root_path
  end

  private

  def set_bar
    @bar = Bar.find(params[:id])
    authorize(@bar)
  end

  def bar_params
    params.require(:bar).permit(:address, :name, :tv_number, :tournament_size, :phone_number, :description, :offers)
  end
end

app/views/bars/index.html.erb
<h1>Bars</h1>
<% @bars.each do |bar| %>
  <p>
    <%= bar.name %>
    <%= bar.phone_number %>
    <%= bar.address %>
    <%= bar.description %>
    <%= bar.tv_number %>
    <%= bar.tournament_size %>
    <%= bar.offers %>
    <%= link_to "See details", bar_path(bar) %>
  </p>
<% end %>

<div id="map" style="width: 100%; height: 600px;"></div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  <% end %>
<% end %>

app/views/bars/show.html.erb
<h1><%= @bar.name %></h1>
  <p>
    <%= @bar.name %>
    <%= @bar.phone_number %>
    <%= @bar.address %>
    <%= @bar.description %>
    <%= @bar.tv_number %>
    <%= @bar.tournament_size %>
    <%= @bar.offers %>
    <%= cl_image_tag(@bar.photo, width: 400, height: 300, crop: :fill) %>
  </p>

<%= link_to "Book this bar and create your tournament!", new_bar_tournament_path(@bar) %>