config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  resources :bars do
    resources :tournaments, only: [:new, :create]
  end
  resources :tournaments, except: [:new, :create] do
    get "playground", to: "tournaments#playground"
    resources :players
    resources :reviews, only: :create
  end
  resources :users
  get "dashboard", to: "users#dashboard"
  resources :scores, only: :update
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "rankings", to: "pages#rankings"

  resources :games, only: [] do
    member do
      patch :update_scores
    end
  end
end

app/models/user.rb
require 'koala'


class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :username, presence: true
  has_many :tournaments, dependent: :destroy
  has_many :players, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)


    user_params[:username] = "#{user_params[:first_name]}#{user_params[:last_name]}"
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    @graph = Koala::Facebook::API.new(user.token)
    profile = @graph.get_object("me")
    @friends = @graph.get_connections("me", "friends")
    return user
  end

  # def self.koala(auth)
  #   access_token = auth['token']
  #   facebook = Koala::Facebook::API.new(access_token)
  #   facebook.get_object("me?fields=name,picture")
  # end



  # def rankings
  #   raise
  #   self.total_goals = 0
  #   if self.players.any?
  #     self.players.each do |player|
  #       if player.scores.any?
  #        player.scores.each do |score|
  #         self.total_goals ||= 0
  #         self.total_goals += score.goals
  #        end
  #       end
  #     end
  #   end
  #   self.save!
  # end


  def rankings
    self.total_against_goals = 0
    self.total_goals = 0
    if self.players != []
      self.players.each do |player|
        if player.scores.first != nil
          Game.all.each do |game|
            unless self.total_goals.nil? || self.total_against_goals.nil? || game.scores.last.goals.nil? || game.scores.first.goals.nil?
            if game.scores.first.player == player
              self.total_goals += game.scores.first.goals
              self.total_against_goals += game.scores.last.goals
            else
              self.total_goals += game.scores.last.goals
              self.total_against_goals += game.scores.first.goals
            end
            self.save
          end
          end
        end
      end
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [ :dashboard, :edit, :update, :destroy ]

  def index
    policy_scope(User)
  end

  def dashboard
    @tournaments = []
    current_user.players.each do |player|
      @tournaments << player.tournament
    end
  end

  def set_user
    authorize(current_user)
  end


end

app/views/users/dashboard.html.erb
<div class="container">
  <h1>My Tournaments</h1>
  <div class="row">
    <% @tournaments.each do |tournament| %>
      <div class="col-xs-12">
        <div class="card"
          style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
             url('<%= cl_image_path tournament.bar.photo, height: 300, width: 400 %>')">
          <%= tournament.user.username %>
          <%= tournament.date %>
          <%= tournament.tournament_type %>
          <%= tournament.bar.name %>
          <% tournament.players.each do |player| %>
            <p>
            <% if @friends != nil %>
              <% @friends.each do |friend| %>
                <% if friend["id"] == player.user.uid %>
                    <% avatar_url = player.user.facebook_picture_url || "http://placehold.it/30x30" %>
                    <%= image_tag avatar_url, class: "avatar dropdown-toggle" %>
                    <img src="" alt="">
                <% end %>
              <% end %>
            <% end %>
          <% end %>
          <%= link_to "See details", tournament_path(tournament) %>
      </div>
    </div>
  <% end %>
  </div>
  <div id="map" style="width: 100%; height: 600px;"></div>
</div>





<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length >= 1) {
          handler.map.centerOn(<%= Geocoder.coordinates(@address) %>);
          handler.getMap().setZoom(<%= @zoom %>);
        }
      });
    });
  <% end %>
<% end %>