config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  resources :bars do
    resources :tournaments, only: [:new, :create]
  end
  resources :tournaments, except: [:new, :create] do
    get "playground", to: "tournaments#playground"
    resources :players
    resources :reviews, only: :create
  end
  resources :users
  get "dashboard", to: "users#dashboard"
  resources :scores, only: :update
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "rankings", to: "pages#rankings"

  resources :games, only: [] do
    member do
      patch :update_scores
    end
  end
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  belongs_to :bar
  belongs_to :user
  has_many :players, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :games, dependent: :destroy


  TOURNAMENT_TYPE = ["small", "medium", "large"]
  STATUS = ["pending", "cancelled", "ready", "past"]
  STEP =  ["group", "round16", "quarter", "semi", "final"]
  NUMBER_PLAYERS = [8, 16, 32]
  NUMBER_CONSOLES = [2, 4, 8]
  NUMBER_GAMES = [15, 31, 63]

  # validates :date, presence: true
  validates :tournament_type, inclusion: { in: TOURNAMENT_TYPE, allow_nil: false }
  validates :step, inclusion: { in: STEP, allow_nil: false }
  # validates :status, inclusion: { in: STATUS }
  # validates :number_players, inclusion: { in: NUMBER_PLAYERS }
  # validates :number_consoles, inclusion: { in: NUMBER_CONSOLES }
  # validates :number_games, inclusion: { in: NUMBER_GAMES }
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_tournament, only: [ :show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [ :index, :show ]
  include PoolRanking

  def index
    policy_scope(Tournament)
    if params[:tournament_address]
      if params[:tournament_address].empty?
        @address = 'Paris'
      else
         @address = params[:tournament_address]
      end
    end
    # @bars = Bar.near(@address, 5).select { |bar| bar.tournaments }
    @radius = 5
    @bars = list_bars(@address, @radius)

    if @bars
      @tournaments = list_tournaments(@bars)
    else
      @tournaments = []
    end

    unless @tournaments.length >= 1
      @radius += 1
      @bars = list_bars(@address, @radius)
      @tournaments = list_tournaments(@bars)
    end

    if @radius < 6
      @zoom = 14
    elsif @radius < 4
      @zoom = 12
    else
      @zoom = 10
    end

    # @tournaments = Tournament.all.joins(:bar).where("bars.latitude IS NOT NULL and bars.longitude IS NOT NULL")
    @hash = Gmaps4rails.build_markers(@tournaments) do |tournament, marker|
      marker.lat tournament.bar.latitude
      marker.lng tournament.bar.longitude
      marker.json({id: tournament.bar.id})
      marker.picture({
        url: ActionController::Base.helpers.image_path('footballball.png'),
        width:  50,
        height: 50
      })
      # marker.infowindow render_to_string(partial: "/tournaments/map_box", locals: { tournament: tournament })
    end

    if current_user
      if current_user.token != nil
        @graph = Koala::Facebook::API.new(current_user.token)
        profile = @graph.get_object("me")
        @friends = @graph.get_connections("me", "friends")
      end
    end

  end

  def show
    @player = Player.new()
    @tournament = (Tournament.joins(:bar).where("bars.latitude IS NOT NULL and bars.longitude IS NOT NULL")).find(params[:id])
    @hash = Gmaps4rails.build_markers(@tournament) do |tournament, marker|
      marker.lat tournament.bar.latitude
      marker.lng tournament.bar.longitude
      # marker.infowindow render_to_string(partial: "/tournaments/map_box", locals: { tournament: tournament })
    end


    @remaining = @tournament.number_players - @tournament.players.count
    @remaining_console_ps4 = remaining_consoles(@tournament)
    @remaining_controllers = remaining_controllers(@tournament)
    @remaining_fifa_game = remaining_fifa_game(@tournament)
    @remaining_total = @remaining_console_ps4 + @remaining_controllers + @remaining_fifa_game
    @current_player = Player.where(tournament: @tournament, user: current_user).first
    if current_user && current_user.token != nil
      @graph = Koala::Facebook::API.new(current_user.token)
      profile = @graph.get_object("me")
      @friends = @graph.get_connections("me", "friends")
    end
    if @remaining == 0 && @remaining_total == 0
      @tournament.status = "ready"
      @tournament.save!
    end
    @review = Review.new()
  end

  def new
    @tournament = Tournament.new()
    @bar = Bar.find(params[:bar_id])
    authorize(@tournament)
  end

  def create
    @tournament = Tournament.new(tournament_params)
    @tournament.user = current_user
    @tournament.step = "group"
    @tournament.bar = Bar.find(params[:bar_id])
    add_params(@tournament)
    authorize(@tournament)
    if @tournament.save
      init_player(@player, @tournament)
      redirect_to tournament_path(@tournament)
    else
      render :new
    end
  end

  def update
    @tournament.update(tournament_params)
    @list_all_players = generate_list_all_players(@tournament)
    if @tournament.save
      if @tournament.step == "group" && @tournament.games == []
        generate_pools(@tournament, @list_all_players)
        redirect_to tournament_playground_path(@tournament)
      elsif @tournament.step == "round16" && @tournament.games.where(step: "round16").order(:name) == []
        ranking_pool(@tournament)
        @winners_pool = classify_pool(@list_all_players)
        generate_round16(@tournament, @winners_pool)
        redirect_to tournament_playground_path(@tournament)
      elsif @tournament.step == "quarter" && @tournament.games.where(step: "quarter").order(:name) == []
        if @tournament.tournament_type == "large"
          @group_games_round16 = @tournament.games.where(step: "round16").order(:name)
          @winners_round16 = classify_after_pool(@group_games_round16)
          generate_quarter(@tournament, @winners_round16)
          redirect_to tournament_playground_path(@tournament)
        elsif @tournament.tournament_type == "medium"
          ranking_pool(@tournament)
          @winners_pool = classify_pool(@list_all_players)
          generate_quarter(@tournament, @winners_pool)
          redirect_to tournament_playground_path(@tournament)
        end
      elsif @tournament.step == "semi" && @tournament.games.where(step: "semi").order(:name) == []
        if @tournament.tournament_type == "small"
          ranking_pool(@tournament)
          @winners_pool = classify_pool(@list_all_players)
          generate_semi(@tournament, @winners_pool)
          redirect_to tournament_playground_path(@tournament)
        elsif
          @group_games_quarter = @tournament.games.where(step: "quarter").order(:name)
          @winners_quarter = classify_after_pool(@group_games_quarter)
          generate_semi(@tournament, @winners_quarter)
          redirect_to tournament_playground_path(@tournament)
        end
      elsif @tournament.step == "final" && @tournament.games.where(step: "final").order(:name) == []
        @group_games_semi = @tournament.games.where(step: "semi").order(:name)
        @winners_semi = classify_after_pool(@group_games_semi)
        generate_final(@tournament, @winners_semi)
        redirect_to tournament_playground_path(@tournament)
      else
        redirect_to tournament_playground_path(@tournament)
      end
    else
      render :new
    end
  end

  def destroy
    @tournament.destroy
    redirect_to tournaments_path
  end

  def playground
    @tournament = Tournament.find(params[:tournament_id])
    authorize(@tournament)
    @list_all_players = generate_list_all_players(@tournament)
    @games = @tournament.games

    if @tournament.step == "group"
      ranking_pool(@tournament)
    end
    @players = classify(@list_all_players)

    @group_games_pool = @games.where(step: "group").order(:name).each_slice(6).to_a

    @group_games_round16 = @games.where(step: "round16").order(:name)
    @group_games_quarter = @games.where(step: "quarter").order(:name)
    @group_games_semi = @games.where(step: "semi").order(:name)
    @group_games_final = @games.where(step: "final").order(:name)

    if @tournament.step == "round16"
      @winners_round16 = classify_after_pool(@group_games_round16)
    elsif @tournament.step == "quarter"
      @winners_quarter = classify_after_pool(@group_games_quarter)
    elsif @tournament.step == "semi"
      @winners_semi = classify_after_pool(@group_games_semi)
    else
      @winner = classify_after_pool(@group_games_final)[0]
    end

  end


  private


  def set_tournament
    @tournament = Tournament.find(params[:id])
    authorize(@tournament)
  end

  def tournament_params
    params.require(:tournament).permit(:bar, :date, :status, :tournament_type, :number_players, :number_consoles, :number_games, :step)
  end

  def add_params(tournament)
    if tournament.tournament_type == "small"
      tournament.number_players = 8
      tournament.number_consoles = 2
      tournament.number_controllers = 4
      tournament.number_games = 2
    elsif tournament.tournament_type == "medium"
      tournament.number_players = 16
      tournament.number_consoles = 4
      tournament.number_controllers = 8
      tournament.number_games = 4
    elsif tournament.tournament_type == "large"
      tournament.number_players = 32
      tournament.number_consoles = 8
      tournament.number_controllers = 16
      tournament.number_games = 8
    end
  end

  def remaining_consoles(tournament)
   consoles_ps4 = 0
    tournament.players.each do |player|
      if player.ps4 == true
        consoles_ps4 += 1
      end
    end
    if consoles_ps4 > tournament.number_consoles
      return 0
    else
      return (tournament.number_consoles - consoles_ps4)
    end
  end

  def remaining_controllers(tournament)
    controllers = 0
    tournament.players.each do |player|
      controllers += player.controller_ps4
    end
    if controllers > tournament.number_controllers
      return 0
    else
      return (tournament.number_controllers - controllers)
    end
  end

  def remaining_fifa_game(tournament)
  fifa_game = 0
    tournament.players.each do |player|
      fifa_game += player.fifa_game_ps4
    end
    if fifa_game > tournament.number_games
      return 0
    else
      return (tournament.number_games - fifa_game)
    end
  end

  def init_player(player, tournament)
    player = Player.new()
    player.user = current_user
    player.tournament = tournament
    player.admin = true
    player.ps4 = false
    player.controller_ps4 = 0
    player.fifa_game_ps4 = 0
    player.save!
  end

  def list_bars(address, radius)
    if address
      bars = Bar.near(address, radius)
    else
      bars = Bar.all
    end

    if params[:players]
      bars = bars.where(tournament_size: params[:players])
    end

    bars
  end

  def list_tournaments(bars)
    bars.map do |bar|
      if params[:date].blank?
        bar.tournaments
      else
        bar.tournaments.where(date: params[:date])
      end
    end.flatten
  end

  def generate_pools(tournament, list_all_players)
    generate_pool_games(list_all_players[0], tournament, "A")
    generate_pool_games(list_all_players[1], tournament, "B")
    if tournament.tournament_type == "medium" || tournament.tournament_type == "large"
      generate_pool_games(list_all_players[2], tournament, "C")

app/helpers/tournament_helper.rb
module TournamentHelper
end

app/views/tournaments/_final_ongoing.html.erb
<div class="col-xs-12 col-sm-12 col-md-10 col-md-10-playground">
  <div class="banner-of-91">
    <div class="banner-for-toggle-group" data-pool="final">
      <div class="banner-for-groups">
        <h2>FINAL</h2>
      </div>
    </div>
    <div class="row row-playground">
      <div class="col-xs-12 col-sm-12 col-md-12 col-md-12-playground">
        <div class="wrapper-to-toggle-calendar" data-pool="final">
          <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-6 col-md-offset-3">
              <% @group_games_final.each do |game| %>
              <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-5">
                  <%= form_for game.scores.first, remote: true do |f| %>
                  <div class="card-team-left">
                    <div class="card-team-left-image">
                      <% if game.scores.first.player.user.facebook_picture_url %>
                      <% avatar_url = game.scores.first.player.user.facebook_picture_url %>
                      <%= image_tag avatar_url, class: "avatar-small" %>
                      <% elsif game.scores.first.player.club? %>
                      <%= image_tag "#{game.scores.first.player.user.link}.jpeg", class: "avatar-small" %>
                      <% elsif %>
                      <% avatar_url = "http://res.cloudinary.com/dutc7zz18/image/upload/v1496741104/avatar-fake_yuue1t.png" %>
                      <%= image_tag avatar_url, class: "avatar" %>
                      <% end %>
                      <div class="card-team-left-image-of-team">
                        <%= image_tag "#{game.scores.first.player.club}.png", class: "team-photo-for-avatar" %>
                      </div>
                    </div>
                    <div class="card-team-left-name">
                      <%= game.scores.first.player.user.first_name.capitalize %>
                    </div>
                    <div class="card-team-left-update-score">
                      <%= f.button class: "card-team-left-score-validate" do %>
                      <i class="fa fa-check fa-check-playground button-non-active-for-scores" aria-hidden="true"></i>
                      <% end %>
                    </div>
                    <div class="card-team-left-score">
                      <%= f.text_field :goals, class: "card-team-left-score-input" %>
                    </div>
                  </div>
                  <% end %>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-5 col-md-offset-1">
                  <%= form_for game.scores.last, remote: true do |f| %>
                  <div class="card-team-right">
                    <div class="card-team-right-score">
                      <%= f.text_field :goals, class: "card-team-right-score-input" %>
                    </div>
                    <div class="card-team-right-update-score">
                      <%= f.button class: "card-team-right-score-validate" do %>
                      <i class="fa fa-check fa-check-playground button-non-active-for-scores" aria-hidden="true"></i>
                      <% end %>
                    </div>
                    <div class="card-team-right-name">
                      <%= game.scores.last.player.user.first_name.capitalize %>&nbsp;&nbsp;
                    </div>
                    <div class="card-team-right-image">
                      <% if game.scores.last.player.user.facebook_picture_url %>
                      <% avatar_url = game.scores.last.player.user.facebook_picture_url %>
                      <%= image_tag avatar_url, class: "avatar-small" %>
                      <% elsif game.scores.last.player.club? %>
                      <%= image_tag "#{game.scores.last.player.user.link}.jpeg", class: "avatar-small" %>
                      <% elsif %>
                      <% avatar_url = "http://res.cloudinary.com/dutc7zz18/image/upload/v1496741104/avatar-fake_yuue1t.png" %>
                      <%= image_tag avatar_url, class: "avatar" %>
                      <% end %>
                      <div class="card-team-right-image-of-team">
                        <%= image_tag "#{game.scores.last.player.club}.png", class: "team-photo-for-avatar" %>
                      </div>
                    </div>
                  </div>
                  <% end %>
                </div>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row row-playground">
      <div class="banner-for-toggle-group" data-pool="final">
        <div class="banner-for-next-step-button">
          <%= form_for @tournament do |f| %>
          <%= f.hidden_field :status, value: "past" %>
          <%= f.submit "CLOSE THE TOURNAMENT", class: "btn btn-primary button-to-next-step" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tournaments/_final_results.html.erb
<div class="col-xs-12 col-sm-12 col-md-10 col-md-10-playground">
  <div class="banner-of-91">
    <div class="row row-playground">
      <div class="col-xs-12 col-sm-12 col-md-12 col-md-12-playground">
        <div class="wrapper-to-toggle-calendar" data-pool="final">
          <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-6 col-md-offset-3">
              <% @group_games_final.each do |game| %>
              <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-5">
                  <%= form_for game.scores.first, remote: true do |f| %>
                     <div class="results-card-team-left">
                <div class="results-card-team-left-image">
                 <% if game.scores.first.player.user.facebook_picture_url %>
                 <% avatar_url = game.scores.first.player.user.facebook_picture_url %>
                 <%= image_tag avatar_url, class: "avatar-small" %>
                 <% elsif game.scores.first.player.club? %>
                 <%= image_tag "#{game.scores.first.player.user.link}.jpeg", class: "avatar-small" %>
                 <% elsif %>
                 <% avatar_url = "http://res.cloudinary.com/dutc7zz18/image/upload/v1496741104/avatar-fake_yuue1t.png" %>
                 <%= image_tag avatar_url, class: "avatar" %>
                 <% end %>
                </div>
                <div class="results-card-team-left-name">
                  <%= game.scores.first.player.user.first_name.capitalize %>
                </div>
                <div class="results-card-team-left-score-def">
                  <%=  game.scores.first.goals %>
                </div>
                <!-- <div class="results-card-team-left-update-score">
                  <#%= f.button class: "results-card-team-left-score-validate" do %>
                  <i class="fa fa-check fa-check-playground button-non-active-for-scores" aria-hidden="true"></i>
                  <#% end %>
                </div>
                <div class="results-card-team-left-score">
                  <#%= f.text_field :goals, class: "results-card-team-left-score-input" %>
                </div> -->
              </div>
                  <% end %>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-5 col-md-offset-1">
                  <%= form_for game.scores.last, remote: true do |f| %>
                  <div class="results-card-team-right">
                <div class="results-card-team-right-score-def">
                  <%=  game.scores.last.goals %>
                </div>
                <!-- <div class="results-card-team-right-score">
                  <#%= f.text_field :goals, class: "results-card-team-right-score-input" %>
                </div>
                <div class="results-card-team-right-update-score">
                  <#%= f.button class: "results-card-team-right-score-validate" do %>
                  <i class="fa fa-check fa-check-playground button-non-active-for-scores" aria-hidden="true"></i>
                  <#% end %>
                </div> -->
                <div class="results-card-team-right-name">
                  <%= game.scores.last.player.user.first_name.capitalize %>&nbsp;&nbsp;
                </div>
                <div class="results-card-team-right-image">
                  <% if game.scores.last.player.user.facebook_picture_url %>
                  <% avatar_url = game.scores.last.player.user.facebook_picture_url %>
                  <%= image_tag avatar_url, class: "avatar-small" %>
                  <% elsif game.scores.last.player.club? %>
                  <%= image_tag "#{game.scores.last.player.user.link}.jpeg", class: "avatar-small" %>
                  <% elsif %>
                  <% avatar_url = "http://res.cloudinary.com/dutc7zz18/image/upload/v1496741104/avatar-fake_yuue1t.png" %>
                  <%= image_tag avatar_url, class: "avatar" %>
                  <% end %>
                </div>
              </div>
                  <% end %>
                </div>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row row-playground">
      <div class="banner-for-toggle-group" data-pool="final">
        <div class="banner-for-gif-cup">
          <%= cl_image_tag("france98_ozkjuv.gif", :width=>500, :crop=>"scale") %>
        </div>
      </div>
    </div>
       <div class="row row-playground">
      <div class="banner-for-toggle-group" data-pool="final">
          <% if @winner %>
          <h1 class="text-center" style="#32B796"><%= @winner.user.first_name %> wins the tournament!</h1>
          <% end %>
      </div>
    </div>
    <div class="row row-playground">
      <div class="banner-for-toggle-group" data-pool="final">
        <div class="banner-for-eimeet-rankings">
          <%= link_to "GO TO EIMEET RANKINGS", rankings_path, class: "btn btn-primary button-to-next-step" %>
        </div>
      </div>
    </div>
  </div>
</div>

<audio style="display: none;" id="sound-of-victory" preload src="/audio/victoire.mp3">

app/views/tournaments/_form_join.html.erb
<label >Which club you will play with?</label>
<select name="league" id="league" class="form-control">
  <option value="LIGUE1">Ligue 1</option>
  <option value="PREMIERELEAGUE">Premiere League</option>
  <option value="LIGA">Liga</option>
</select>

<select name="LIGUE1" id="0" class="clubs form-control">
<% ["Choose your team", "Angers", "Bastia", "Bordeaux", "Caen", "Dijon", "Guingamp", "Lille", "Lorient", "Lyon", "Marseille", "Metz", "Monaco", "Montpellier", "Nancy", "Nantes", "Nice", "Paris-SG", "Rennes", "Saint-Etienne", "Toulouse"].each do |club| %>

<option value="<%= club %>"><%= club %></option>
<% end %>
</select>


<select name="PREMIERELEAGUE" id="1" class="hidden clubs form-control">
<% ["Choose your team", "Arsenal", "Bournemouth", "Burnley", "Chelsea", "CrystalPalace", "Everton", "Hull", "Leicester", "Liverpool", "ManchesterCity", "ManchesterUnited", "Middlesbrough", "Southampton", "Stoke", "Sunderland", "Swansea", "Tottenham", "Watford", "WestBromwichAlbion", "WestHam"].each do |club| %>
<option value="<%= club %>"><%= club %></option>
<% end %>
</select>

<!-- test -->
<select name="Liga" id="2" class="hidden clubs form-control">
<% ["Choose your team", "Alavés", "AthleticBilbao", "AtléticodeMadrid", "BetisSéville", "CeltaVigo", "DeportivoLaCorogne", "Eibar", "EspanyolBarcelone", "FCBarcelone", "GranadaCF", "LasPalmas", "Leganés", "Malaga", "Osasuna", "RealMadrid", "RealSociedad", "SportingGijon", "SévilleFC", "ValenceCF"].each do |club| %>
<option value="<%= club %>"><%= club %></option>
<% end %>
</select>


<%= simple_form_for [@tournament, @player] do |f| %>


  <%= f.input :club, label: false, input_html: {class: 'hidden', id: 'club_choice'} %>


  <label for="ps4">Bring your PS4?</label>
  <%= f.input :ps4, as: :radio_buttons, label: false, item_wrapper_tag: false, wrapper_html: {class: 'brand-choice'}  %>
  <label for="controller_ps4">Bring controllers?</label>
  <%= f.input :controller_ps4, as: :radio_buttons, collection: 0..4, label: false, item_wrapper_tag: false, wrapper_html: {class: 'controller-choice'}  %>
  <label for="fifa_game_ps4">Bring Fifa?</label>
  <%= f.input :fifa_game_ps4, as: :radio_buttons, collection: 0..2, label: false, item_wrapper_tag: false, wrapper_html: {class: 'fifa-choice'}  %>
  <%= f.submit "JOIN", class: "btn btn-primary btn-primary-update" %>
<% end %>




<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      $('#league').change(function(){
      var team = $('#league').val();
      console.log(team)

      if (team == 'LIGUE1') {
        $('#1').addClass( "hidden" )
        $('#0').removeClass( "hidden" )
        $('#2').addClass( "hidden" )
      } else if (team == 'PREMIERELEAGUE') {
      $('#0').addClass( "hidden" )
      $('#1').removeClass( "hidden" )
      $('#2').addClass( "hidden" )

      } else if (team == 'LIGA') {
      $('#0').addClass( "hidden" )
      $('#1').addClass( "hidden" )
      $('#2').removeClass( "hidden" )

      }
      });


      $('#0').change(function(){
      var team = $('#0').val();
      $('#club_choice').val(team);
      console.log(team)
    });
    $('#1').change(function(){
      var team = $('#1').val();
      $('#club_choice').val(team);
      console.log(team)
    });
    $('#2').change(function(){
      var team = $('#2').val();
      $('#club_choice').val(team);
      console.log(team)
    });

    });
  <% end %>
<% end %>

app/views/tournaments/_list-players.html.erb
<div class="list-players">
  <div class="list-players-avatar">
    <% if player.user.facebook_picture_url %>
      <% avatar_url = player.user.facebook_picture_url %>
      <%= image_tag avatar_url, class: "avatar" %>
    <% end %>
  </div>
  <div class="list-players-username">
    <span class="username-player"><%= player.user.username %></span>
  </div>
  <div class="list-players-material">
    <% if player.ps4 == true %>
      <span class="color-fire">1 x</span> <%= image_tag "ps4.png", class: "icon"%>
    <% end %>
    <% if player.controller_ps4 > 0 %>
      <span class="color-fire"><%= player.controller_ps4 %> x</span> <%= image_tag "manette.png", class: "icon" %>
    <% end %>
    <% if player.fifa_game_ps4 > 0 %>
      <span class="color-fire"><%= player.fifa_game_ps4 %> x</span> <%= image_tag "fifa.png", class: "icon" %>
    <% end %>
  </div>
  <div class="list-players-actions">
    <% if policy(player).destroy? %>
      <%= link_to tournament_player_path(@tournament, player),
        method: :delete,
        data: { confirm: "Are you sure?" } do %>
      <i class="fa fa-trash-o" aria-hidden="true"></i>
    <% end %>
  <% end %>
  &nbsp;
  <% if policy(player).update? %>
    <% if  @remaining_console_ps4 != 0 || @remaining_controllers != 0 || @remaining_fifa_game != 0 %>
      <i class="fa fa-pencil fa-pencil-active" aria-hidden="true"></i>
    <% else %>
      <i class="fa fa-pencil fa-pencil-disabled" aria-hidden="true"></i>
    <% end %>
  <% end %>
  </div>
  <div class="list-players-team">
  </div>
</div>

app/views/tournaments/_ranking_all.html.erb
<% @players.each do |pool_sort| %>
<div class="wrapper-to-toggle-ranking" data-pool="<%= pool_sort.first.scores.first.game.name %>">
  <div class="ranking">
    <div class="ranking-header">
      <div class="ranking-header-rank"></div>
      <div class="ranking-header-team"></div>
      <div class="ranking-header-pts">PTS</div>
      <div class="ranking-header-bp">GF</div>
      <div class="ranking-header-bc">GA</div>
      <div class="ranking-header-diff">GD</div>
    </div>
    <% pool_sort.each_with_index do |player, index| %>
    <div class="ranking-each-team">
      <div class="ranking-each-team-number ranking-each-team-number-rank">
        <%= index + 1 %>
      </div>
      <div class="ranking-each-team-infos">
        <div class="ranking-each-team-infos-avatar">
          <% if player.user.facebook_picture_url %>
          <% avatar_url = player.user.facebook_picture_url %>
          <%= image_tag avatar_url, class: "avatar-small" %>
          <% elsif player.club? %>
          <%= image_tag "#{player.user.link}.jpeg", class: "avatar-small" %>
          <% elsif %>
          <% avatar_url = "http://res.cloudinary.com/dutc7zz18/image/upload/v1496741104/avatar-fake_yuue1t.png" %>
          <%= image_tag avatar_url, class: "avatar" %>
          <% end %>
        </div>
        <div class="ranking-each-team-infos-name">
          <%= player.user.first_name %>
        </div>
      </div>
      <div class="ranking-each-team-number">
        <%= player.points %>
      </div>
      <div class="ranking-each-team-number">
        <%= player.bp %>
      </div>
      <div class="ranking-each-team-number">
        <%= player.bc %>
      </div>
      <div class="ranking-each-team-number">
        <%= player.diff %>
      </div>
    </div>
    <% end %>
  </div>
</div>
<% end %>