config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  resources :bars do
    resources :tournaments, only: [:new, :create]
  end
  resources :tournaments, except: [:new, :create] do
    get "playground", to: "tournaments#playground"
    resources :players
    resources :reviews, only: :create
  end
  resources :users
  get "dashboard", to: "users#dashboard"
  resources :scores, only: :update
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "rankings", to: "pages#rankings"

  resources :games, only: [] do
    member do
      patch :update_scores
    end
  end
end

app/views/shared/_card.html.erb
<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('background.jpg');">>
  <div class="card-bar">
  <h2><%= tournament.bar.name %></h2>
  <p><%= tournament.bar.address %></p>
  </div>
  <div class="card-info">
    <div class="card-info-date">
      <p><i class="fa fa-clock-o" aria-hidden="true"></i><%= tournament.date %></p>
    </div>
    <div class="card-info-players">
      <p><i class="fa fa-users" aria-hidden="true"></i><%= tournament.players.count %>/<%= tournament.number_players %></p>
    </div>
    <div class="card-info-facebook">

    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible hideMe" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(30,30,30,0.6) 0%, rgba(30,30,30,0.6) 50%), url('<%= cl_image_path('background-test_yrp3fo') %>');">
  <div class="banner-content">
    <h1 style="color:#FAFAFA; font-size:48px;">Playing offline <span style="color:#A92222;">FIFA</span> tournaments</h1>
    <!-- <p>In bars, with friends and players...</p> -->
    <div class="form-homepage">
      <%= form_tag tournaments_path, method: :get, class: "form-group form-group-header form-inline" do %>

        <%= text_field_tag 'tournament_address', '', class: "form-control form-control-header", placeholder: "Type your address" %>
        <%= button_tag(type: "submit", class: "btn btn-primary btn-primary-header", id: "get_current_position") do %>
          <i class="fa fa-location-arrow" aria-hidden="true"></i>
        <% end %>

        <%= submit_tag 'GO', class: 'btn btn-primary btn-primary-header' %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "eimeet_logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->

    <%= link_to t(".sign_in", default: "Join"), tournaments_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <%= link_to t(".sign_in", default: "Create"), "#", class: "navbar-wagon-item navbar-wagon-link disabled create-btn" %>

    <% if user_signed_in? %>

    <!-- Profile picture and dropdown -->
      <%= link_to destroy_user_session_path, class: "navbar-wagon-item navbar-wagon-link-log-out toggle-menu-content hidden create-btn", method: :delete do %>
        <%= t(".sign_out", default: "Log out") %>
      <% end %>

      <%= link_to t(".sign_in", default: "My Tournaments"), "#", class: "navbar-wagon-item navbar-wagon-link-account disabled create-btn toggle-menu-content hidden" %>


      <% avatar_url = current_user.facebook_picture_url || current_user.first_name %>
      <% if current_user.facebook_picture_url %>
        <%= image_tag avatar_url, class: "avatar navbar-wagon-item navbar-wagon-link toggle-menu" %>
      <% else %>
      <div class="navbar-wagon-item navbar-wagon-link-account toggle-menu"><%= current_user.first_name %></div>
      <% end %>


      <% else %>
    <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <i class="fa fa-bars fa-bars-navbar"></i>
    <i class="fa fa-times hidden"></i>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-12 text-center full-screen-menu hidden">
      <div class="links-item">
        <%= link_to t(".sign_in", default: "Join"), tournaments_path, class: "navbar-wagon-item navbar-wagon-link-mobile" %>
      </div>
      <div class="links-item">
        <%= link_to t(".sign_in", default: "Create"), "#", class: "navbar-wagon-item navbar-wagon-link-mobile" %>
      </div>
      <% if user_signed_in? %>
      <div class="links-item">
        <%= link_to t(".sign_in", default: "Tournaments"), "#", class: "navbar-wagon-item navbar-wagon-link-mobile" %>
      </div>
      <div class="links-item">
        <hr style="border: none; height: 2px; width: 200px;, text-align: center; color: #FAFAFA; background: #FAFAFA;"/>
      </div>
      <div class="links-item">
        <%= link_to destroy_user_session_path, class: "navbar-wagon-item navbar-wagon-link-mobile", method: :delete do %>
        <%= t(".sign_out", default: "Log out") %>
        <% end %>
      </div>
      <% else %>
      <div class="links-item">
        <hr style="border: none; height: 2px; width: 200px;, text-align: center; color: #FAFAFA; background: #FAFAFA;"/>
      </div>
      <div class="links-item">
        <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link-mobile" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_progress-bar-in.html.erb
<% if tournament.number_players == 8 %>
  <% if tournament.players.count <= 2 %>
    <div class="progress">
      <div class="progress-bar-green" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="width: 25%;">
        You are registered
      </div>
    </div>
  <% elsif tournament.players.count <= 3 %>
    <div class="progress">
      <div class="progress-bar-green" role="progressbar" aria-valuenow="38" aria-valuemin="0" aria-valuemax="100" style="width: 38%;">
        You are registered
      </div>
    </div>
  <% elsif tournament.players.count <= 4 %>
    <div class="progress">
      <div class="progress-bar-green" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%;">
        You are registered
      </div>
    </div>
  <% elsif tournament.players.count <= 5 %>
    <div class="progress">
      <div class="progress-bar-orange" role="progressbar" aria-valuenow="63" aria-valuemin="0" aria-valuemax="100" style="width: 63%;">
        You are registered
      </div>
    </div>
  <% elsif tournament.players.count <= 6 %>
    <div class="progress">
      <div class="progress-bar-green" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 75%;">
        You are registered
      </div>
    </div>
  <% elsif tournament.players.count < 8 %>
    <div class="progress">
      <div class="progress-bar-green" role="progressbar" aria-valuenow="88" aria-valuemin="0" aria-valuemax="100" style="width: 88%;">
        You are registered
      </div>
    </div>
  <% elsif tournament.players.count == 8 %>
    <div class="progress">
      <div class="progress-bar-green" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
        You are registered
      </div>
    </div>
  <% end %>
<% elsif tournament.number_players == 16 %>
  <% if tournament.players.count <= 2 %>
    <div class="progress">
      <div class="progress-bar-green" role="progressbar" aria-valuenow="13" aria-valuemin="0" aria-valuemax="100" style="width: 13%;">
        You are registered
      </div>
    </div>
  <% elsif tournament.players.count <= 4 %>
    <div class="progress">
      <div class="progress-bar-green" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="width: 25%;">
        You are registered
      </div>
    </div>
  <% elsif tournament.players.count <= 6 %>
    <div class="progress">
      <div class="progress-bar-green" role="progressbar" aria-valuenow="38" aria-valuemin="0" aria-valuemax="100" style="width: 38%;">
        You are registered
      </div>
    </div>
  <% elsif tournament.players.count <= 8 %>
    <div class="progress">
      <div class="progress-bar-green" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%;">
        You are registered
      </div>
    </div>
  <% elsif tournament.players.count <= 10 %>
    <div class="progress">
      <div class="progress-bar-green" role="progressbar" aria-valuenow="63%" aria-valuemin="0" aria-valuemax="100" style="width: 63%%;">
        You are registered
      </div>
    </div>
  <% elsif tournament.players.count <= 12 %>
    <div class="progress">
      <div class="progress-bar-green" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 75%;">
        You are registered
      </div>
    </div>
  <% elsif tournament.players.count < 16 %>
    <div class="progress">
      <div class="progress-bar-green" role="progressbar" aria-valuenow="88" aria-valuemin="0" aria-valuemax="100" style="width: 88%;">
        You are registered
      </div>
    </div>
  <% elsif tournament.players.count == 16 %>
    <div class="progress">
      <div class="progress-bar-green" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
        You are registered
      </div>
    </div>
  <% end %>

<% elsif tournament.number_players == 32 %>
  <% if tournament.players.count <= 4 %>
    <div class="progress">
      <div class="progress-bar-green" role="progressbar" aria-valuenow="13" aria-valuemin="0" aria-valuemax="100" style="width: 13%;">
        You are registered
      </div>
    </div>
  <% elsif tournament.players.count <= 8 %>
    <div class="progress">
      <div class="progress-bar-green" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="width: 25%;">
        You are registered
      </div>
    </div>
  <% elsif tournament.players.count <= 12 %>
    <div class="progress">
      <div class="progress-bar-green" role="progressbar" aria-valuenow="38" aria-valuemin="0" aria-valuemax="100" style="width: 38%;">
        You are registered
      </div>
    </div>
  <% elsif tournament.players.count <= 16 %>
    <div class="progress">
      <div class="progress-bar-green" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%;">
        You are registered
      </div>
    </div>
  <% elsif tournament.players.count <= 20 %>
    <div class="progress">
      <div class="progress-bar-green" role="progressbar" aria-valuenow="63" aria-valuemin="0" aria-valuemax="100" style="width: 63%;">
        You are registered
      </div>
    </div>
  <% elsif tournament.players.count <= 24 %>
    <div class="progress">
      <div class="progress-bar-green" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 75%;">
        You are registered
      </div>
    </div>
  <% elsif tournament.players.count < 32 %>
    <div class="progress">
      <div class="progress-bar-green" role="progressbar" aria-valuenow="88" aria-valuemin="0" aria-valuemax="100" style="width: 88%;">
        You are registered
      </div>
    </div>
  <% elsif tournament.players.count <= 32 %>
    <div class="progress">
      <div class="progress-bar-green" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
        You are registered
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_progress-bar-show-in.html.erb
<% if tournament.number_players == 8 %>
  <% if tournament.players.count <= 2 %>
    <div class="progress">
      <div class="progress-bar-green-show" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="width: 25%;">
        YOU ARE REGISTERED - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count <= 3 %>
    <div class="progress">
      <div class="progress-bar-green-show" role="progressbar" aria-valuenow="38" aria-valuemin="0" aria-valuemax="100" style="width: 38%;">
        YOU ARE REGISTERED - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count <= 4 %>
    <div class="progress">
      <div class="progress-bar-green-show" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%;">
        YOU ARE REGISTERED - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count <= 5 %>
    <div class="progress">
      <div class="progress-bar-green-show" role="progressbar" aria-valuenow="63" aria-valuemin="0" aria-valuemax="100" style="width: 63%;">
        BOOK FAST - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count <= 6 %>
    <div class="progress">
      <div class="progress-bar-green-show" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 75%;">
        YOU ARE REGISTERED - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count < 8 %>
    <div class="progress">
      <div class="progress-bar-green-show" role="progressbar" aria-valuenow="88" aria-valuemin="0" aria-valuemax="100" style="width: 88%;">
        <% if remaining == 1 %>
          YOU ARE REGISTERED - <%= remaining %> SPOT REMAINING
        <% else %>
          YOU ARE REGISTERED - <%= remaining %> SPOTS REMAINING
        <% end %>
      </div>
    </div>
  <% elsif tournament.players.count == 8 %>
    <div class="progress">
      <div class="progress-bar-green-show" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
        YOU ARE REGISTERED - TOURNAMENT FULL
      </div>
    </div>
  <% end %>
<% elsif tournament.number_players == 16 %>
  <% if tournament.players.count <= 2 %>
    <div class="progress">
      <div class="progress-bar-green-show" role="progressbar" aria-valuenow="13" aria-valuemin="0" aria-valuemax="100" style="width: 13%;">
        YOU ARE REGISTERED - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count <= 4 %>
    <div class="progress">
      <div class="progress-bar-green-show" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="width: 25%;">
        YOU ARE REGISTERED - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count <= 6 %>
    <div class="progress">
      <div class="progress-bar-green-show" role="progressbar" aria-valuenow="38" aria-valuemin="0" aria-valuemax="100" style="width: 38%;">
        YOU ARE REGISTERED - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count <= 8 %>
    <div class="progress">
      <div class="progress-bar-green-show" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%;">
        YOU ARE REGISTERED - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count <= 10 %>
    <div class="progress">
      <div class="progress-bar-green-show" role="progressbar" aria-valuenow="63%" aria-valuemin="0" aria-valuemax="100" style="width: 63%%;">
        YOU ARE REGISTERED - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count <= 12 %>
    <div class="progress">
      <div class="progress-bar-green-show" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 75%;">
        YOU ARE REGISTERED - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count < 16 %>
    <div class="progress">
      <div class="progress-bar-green-show" role="progressbar" aria-valuenow="88" aria-valuemin="0" aria-valuemax="100" style="width: 88%;">
        <% if remaining == 1 %>
          YOU ARE REGISTERED - <%= remaining %> SPOT REMAINING
        <% else %>
          YOU ARE REGISTERED - <%= remaining %> SPOTS REMAINING
        <% end %>
      </div>
    </div>
  <% elsif tournament.players.count == 16 %>
    <div class="progress">
      <div class="progress-bar-red-show" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
        YOU ARE REGISTERED - TOURNAMENT FULL
      </div>
    </div>
  <% end %>

<% elsif tournament.number_players == 32 %>
  <% if tournament.players.count <= 4 %>
    <div class="progress">
      <div class="progress-bar-green-show" role="progressbar" aria-valuenow="13" aria-valuemin="0" aria-valuemax="100" style="width: 13%;">
        YOU ARE REGISTERED - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count <= 8 %>
    <div class="progress">
      <div class="progress-bar-green-show" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="width: 25%;">
        YOU ARE REGISTERED - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count <= 12 %>
    <div class="progress">
      <div class="progress-bar-green-show" role="progressbar" aria-valuenow="38" aria-valuemin="0" aria-valuemax="100" style="width: 38%;">
        YOU ARE REGISTERED - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count <= 16 %>
    <div class="progress">
      <div class="progress-bar-green-show" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%;">
        YOU ARE REGISTERED - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count <= 20 %>
    <div class="progress">
      <div class="progress-bar-green-show" role="progressbar" aria-valuenow="63" aria-valuemin="0" aria-valuemax="100" style="width: 63%;">
        YOU ARE REGISTERED - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count <= 24 %>
    <div class="progress">
      <div class="progress-bar-green-show" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 75%;">
        YOU ARE REGISTERED - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count < 32 %>
    <div class="progress">
      <div class="progress-bar-green-show" role="progressbar" aria-valuenow="88" aria-valuemin="0" aria-valuemax="100" style="width: 88%;">
        <% if remaining == 1 %>
          YOU ARE REGISTERED - <%= remaining %> SPOT REMAINING
        <% else %>
          YOU ARE REGISTERED - <%= remaining %> SPOTS REMAINING
        <% end %>
      </div>
    </div>
  <% elsif tournament.players.count <= 32 %>
    <div class="progress">
      <div class="progress-bar-red-show" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
        YOU ARE REGISTERED - TOURNAMENT FULL
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_progress-bar-show.html.erb
<% if tournament.number_players == 8 %>
  <% if tournament.players.count <= 2 %>
    <div class="progress">
      <div class="progress-bar-orange-show" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="width: 25%;">
        REGISTRATION OPEN - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count <= 3 %>
    <div class="progress">
      <div class="progress-bar-orange-show" role="progressbar" aria-valuenow="38" aria-valuemin="0" aria-valuemax="100" style="width: 38%;">
        REGISTRATION OPEN - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count <= 4 %>
    <div class="progress">
      <div class="progress-bar-orange-show" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%;">
        REGISTRATION OPEN - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count <= 5 %>
    <div class="progress">
      <div class="progress-bar-orange-show" role="progressbar" aria-valuenow="63" aria-valuemin="0" aria-valuemax="100" style="width: 63%;">
        BOOK FAST - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count <= 6 %>
    <div class="progress">
      <div class="progress-bar-orange-show" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 75%;">
        ALMOST FULL! - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count < 8 %>
    <div class="progress">
      <div class="progress-bar-orange-show" role="progressbar" aria-valuenow="88" aria-valuemin="0" aria-valuemax="100" style="width: 88%;">
        <% if remaining == 1 %>
          HURRY UP! - <%= remaining %> SPOT REMAINING
        <% else %>
          HURRY UP! - <%= remaining %> SPOTS REMAINING
        <% end %>
      </div>
    </div>
  <% elsif tournament.players.count == 8 %>
    <div class="progress">
      <div class="progress-bar-red-show" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
        TOURNAMENT FULL
      </div>
    </div>
  <% end %>
<% elsif tournament.number_players == 16 %>
  <% if tournament.players.count <= 2 %>
    <div class="progress">
      <div class="progress-bar-orange-show" role="progressbar" aria-valuenow="13" aria-valuemin="0" aria-valuemax="100" style="width: 13%;">
        REGISTRATION OPEN - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count <= 4 %>
    <div class="progress">
      <div class="progress-bar-orange-show" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="width: 25%;">
        REGISTRATION OPEN - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count <= 6 %>
    <div class="progress">
      <div class="progress-bar-orange-show" role="progressbar" aria-valuenow="38" aria-valuemin="0" aria-valuemax="100" style="width: 38%;">
        REGISTRATION OPEN - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count <= 8 %>
    <div class="progress">
      <div class="progress-bar-orange-show" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%;">
        REGISTRATION OPEN - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count <= 10 %>
    <div class="progress">
      <div class="progress-bar-orange-show" role="progressbar" aria-valuenow="63%" aria-valuemin="0" aria-valuemax="100" style="width: 63%%;">
        BOOK FAST! - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count <= 12 %>
    <div class="progress">
      <div class="progress-bar-orange-show" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 75%;">
        ALMOST FULL! - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count < 16 %>
    <div class="progress">
      <div class="progress-bar-orange-show" role="progressbar" aria-valuenow="88" aria-valuemin="0" aria-valuemax="100" style="width: 88%;">
        <% if remaining == 1 %>
          HURRY UP! - <%= remaining %> SPOT REMAINING
        <% else %>
          HURRY UP! - <%= remaining %> SPOTS REMAINING
        <% end %>
      </div>
    </div>
  <% elsif tournament.players.count == 16 %>
    <div class="progress">
      <div class="progress-bar-red-show" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
        TOURNAMENT FULL
      </div>
    </div>
  <% end %>

<% elsif tournament.number_players == 32 %>
  <% if tournament.players.count <= 4 %>
    <div class="progress">
      <div class="progress-bar-orange-show" role="progressbar" aria-valuenow="13" aria-valuemin="0" aria-valuemax="100" style="width: 13%;">
        REGISTRATION OPEN - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count <= 8 %>
    <div class="progress">
      <div class="progress-bar-orange-show" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="width: 25%;">
        REGISTRATION OPEN - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count <= 12 %>
    <div class="progress">
      <div class="progress-bar-orange-show" role="progressbar" aria-valuenow="38" aria-valuemin="0" aria-valuemax="100" style="width: 38%;">
        REGISTRATION OPEN - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count <= 16 %>
    <div class="progress">
      <div class="progress-bar-orange-show" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%;">
        REGISTRATION OPEN - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count <= 20 %>
    <div class="progress">
      <div class="progress-bar-orange-show" role="progressbar" aria-valuenow="63" aria-valuemin="0" aria-valuemax="100" style="width: 63%;">
        BOOK FAST! - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count <= 24 %>
    <div class="progress">
      <div class="progress-bar-orange-show" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 75%;">
        ALMOST FULL! - <%= remaining %> SPOTS REMAINING
      </div>
    </div>
  <% elsif tournament.players.count < 32 %>
    <div class="progress">
      <div class="progress-bar-orange-show" role="progressbar" aria-valuenow="88" aria-valuemin="0" aria-valuemax="100" style="width: 88%;">
        <% if remaining == 1 %>
          HURRY UP! - <%= remaining %> SPOT REMAINING
        <% else %>
          HURRY UP! - <%= remaining %> SPOTS REMAINING
        <% end %>
      </div>
    </div>
  <% elsif tournament.players.count <= 32 %>
    <div class="progress">
      <div class="progress-bar-red-show" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
        TOURNAMENT FULL
      </div>
    </div>
  <% end %>
<% end %>